VIA_ENABLE = yes
CAPS_WORD_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
OPT_DEFS += -DDYNAMIC_KEYMAP_LAYER_COUNT=10
OPT_DEFS += -DDYNAMIC_KEYMAP_MACRO_COUNT=42
OPT_DEFS += -DWEAR_LEVELING_LOCAL_SIZE=30720
