VIA_ENABLE = yes
# AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
# COMBO_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
MOUSE_ENABLE = yes
TAP_DANCE_ENABLE = yes
OPT_DEFS += -DDYNAMIC_KEYMAP_LAYER_COUNT=11
OPT_DEFS += -DDYNAMIC_KEYMAP_MACRO_COUNT=16
