VIA_ENABLE = yes
CAPS_WORD_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
OPT_DEFS += -DDYNAMIC_KEYMAP_LAYER_COUNT=11
OPT_DEFS += -DDYNAMIC_KEYMAP_MACRO_COUNT=16
MOUSE_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
